export const DISPATCH_ACTION = {
  sales: 'sales',
  totalCalls: 'total calls',
  freeCalls: 'free calls',
  appsConverted: 'appsConverted',
  nps: 'nps', 
  // addSalesTarget: "add sales target",
  // addSalesKpi: "add sales kpi",
  // addTotalCallsTarget: "add total calls target",
  // addTotalCallsKpi: "add total calls kpi",
  // addAppsConvertedTarget: "add apps converted target",
  // addAppsConvertedKpi: "add apps converted target kpi",
  // addFreeCallsTarget: "add free calls target",
  // addFreeCallsKpi: "add free calls kpi",
  // addNpsTarget: "add nps target",
  // addNpsKpi: "add nps kpi",
};
