import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { BonusCategoryLanding } from "../components/bonusCategoryLanding";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Bonus Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="text-align">this is where the body of the app will be</h1>
        <>
          <BonusCategoryLanding />
        </>
      </main>
    </div>
  );
}
